# **PyTorch Tensors**
> PyTorch tensors are multi-dimensional arrays, similar to arrays in [`Numpy`](https://numpy.org/) but with additional features that make them suitable for _deep learning_

> 📝 **Note**
+ The [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor) class is the fundamental / central data structures in PyTorch

In [ ]:
# import pytorch
import torch

# print the version
print(torch.__version__)

2.5.0+cu121


## **Creating tensors**
> PyTorch tensors can be of various types: _scalar_, _vector_, _matrix_ and _tensor_
+ To create a tensor with pre-existing data, use [`torch.tensor()`](https://pytorch.org/docs/stable/generated/torch.tensor.html#torch-tensor) constructor
+ Find link to documentation [`here`](https://pytorch.org/docs/stable/tensors.html)

### Scalar
+ A _scalar_ is a _zero-dimension_ single number


In [ ]:
sc = torch.tensor(7)
sc

tensor(7)

+ `Tensor.item` returns the value of this tensor as a standard Python number.
> Only works for tensors with one item though

In [ ]:
# get item
sc.item()

7

+ `Tensor.dim()` or `Tensor.ndim` returns the number of dimensions of the tensor.

In [ ]:
# find dimensions
sc.ndim

0

### Vector
+ A _vector_ is a _single dimension_ tensor but can contain many numbers

In [ ]:
vt = torch.tensor([7, 3, 5])
vt

tensor([7, 3, 5])

In [ ]:
# get dimensions
vt.ndim

1

+ `Tesor.shape` or `Tensor.size()` returns the size of the tensor

In [ ]:
# shape
vt.shape

torch.Size([3])

### MATRIX
+ A _MATRIX_ is a _vector_, but with an extra dimension

In [ ]:
MATRIX = torch.tensor([[7, 8, 9],
                       [3, 4, 5]])

MATRIX

tensor([[7, 8, 9],
        [3, 4, 5]])

In [ ]:
# shape
MATRIX.shape

torch.Size([2, 3])

In [ ]:
# dimensions
MATRIX.ndim

2

+ The contents of a tensor can be accessed and modified using Python’s indexing

In [ ]:
MATRIX[0]

tensor([7, 8, 9])

In [ ]:
MATRIX[1]

tensor([3, 4, 5])

### TENSOR
+ This is an _n-dimensional_ array of numbers

In [ ]:
TENSOR = torch.tensor([[[1, 2],
                        [3, 6],
                        [7, 9]],
                        [[[3, 4],
                        [5, 7],
                        [6, 8]]]])

TENSOR

tensor([[[1, 2],
         [3, 6],
         [7, 9]],

        [[3, 4],
         [5, 7],
         [6, 8]]])

In [ ]:
# shape
TENSOR.shape

torch.Size([2, 1, 3, 2])

In [ ]:
# dimensions
TENSOR.ndim

3

In [ ]:
# zeroth axis
TENSOR[0]

tensor([[1, 2],
        [3, 6],
        [7, 9]])

In [ ]:
# first axis
TENSOR[1]

tensor([[3, 4],
        [5, 7],
        [6, 8]])

> ▶️ **Up Next**  

> Random tensors