# **[`torch.arange`](https://pytorch.org/docs/stable/generated/torch.arange.html#torch-arange)**
> Sometimes you might want a range of numbers, such as `1` to `10` or `0` to `100`

```
torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None,
      requires_grad=False)
```

In [1]:
# import torch
import torch
torch.__version__

'2.5.1+cu121'

In [ ]:
# 0 to 10
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# size
one_to_ten.shape

torch.Size([10])

In [ ]:
# with a step of 2
torch.arange(2, 22, 2)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# **[`torch.linspace`](https://pytorch.org/docs/stable/generated/torch.linspace.html#torch-linspace)**
```
torch.linspace(start, end, steps, *, out=None, dtype=None,  
    layout=torch.strided, device=None, requires_grad=False)
```
> Creates a one-dimensional tensor of size `steps` whose values are evenly spaced from `start` to `end`, inclusive

In [3]:
torch.linspace(start=4, end=10, steps=16)

tensor([ 4.0000,  4.4000,  4.8000,  5.2000,  5.6000,  6.0000,  6.4000,  6.8000,
         7.2000,  7.6000,  8.0000,  8.4000,  8.8000,  9.2000,  9.6000, 10.0000])

# **[`torch.zeros_like`](https://pytorch.org/docs/stable/generated/torch.ones_like.html#torch-ones-like)**
```
torch.ones_like(input, *, dtype=None, layout=None, device=None, requires_grad=False,
    memory_format=torch.preserve_format)
```
> Returns a tensor filled with the scalar value `1`, with the same size as `input`

In [ ]:
torch.ones_like(one_to_ten)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# **[`torch.zeros_like`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html#torch-zeros-like)**
```
torch.zeros_like(input, *, dtype=None, layout=None, device=None, requires_grad=False,
    memory_format=torch.preserve_format)
```
> Returns a tensor filled with the scalar value `0`, with the same size as `input`

In [ ]:
# create random tensor
rand_tensor = torch.rand(2, 2, 3)
rand_tensor

tensor([[[0.9765, 0.2128, 0.8815],
         [0.2054, 0.9880, 0.6675]],

        [[0.5165, 0.0335, 0.5286],
         [0.4719, 0.8609, 0.0951]]])

In [ ]:
# create a tensor of zeros but same shape as above
torch.zeros_like(rand_tensor)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

> ▶️ **Up Next**  

> Tensor data types