<a href="https://colab.research.google.com/github/Martinmbiro/PyTorch-tensor-basics/blob/main/06%20Basic%20tensor%20operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensor Operations**
> In deep leaning, data (images, text, audio, e.t.c) is represented as _tensors_  

> Then, a _Neural Network_ will be comprised of mathematical functions that Pytorch is going to run on the data, to create a representation of the patterns in the input *data*. Some basic operations include the following:
+ Addition
+ Subtraction
+ Division
+ Matrix multiplication
+ Element-wise multiplication

> **Reference** 📚   
+ More Mathematical operations can be found in the Pytorch documentation linked [`here`](https://pytorch.org/docs/stable/torch.html#math-operations)

In [ ]:
# import torch
import torch
print(torch.__version__)

2.5.1+cu121


## Addition
> Can be achieved using [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html#torch-add) or normal python addition `+` operator
+ `torch.add()` adds `other`, scaled by `alpha`, to `input`

```
  torch.add(input, other, *, alpha=1, out=None)
```
> **Parameters**
+ `input` (Tensor) – the input tensor.
+ `other` (Tensor or Number) – the tensor or number to add to `input`
+ `alpha` (Number) – the multiplier for `other`
+ `out` (Tensor, optional) – the output tensor


In [ ]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [ ]:
# using addition symbol
a + 10

tensor([11, 12, 13])

In [ ]:
# using torch.add() function
b = torch.rand(3, 1)
b

tensor([[0.3126],
        [0.2078],
        [0.1652]])

In [ ]:
torch.add(b, 10)

tensor([[10.3126],
        [10.2078],
        [10.1652]])

In [ ]:
c = torch.rand(3)
c

tensor([0.9641, 0.9762, 0.4767])

In [ ]:
torch.add(b, c, alpha=10)

tensor([[ 9.9533, 10.0744,  5.0794],
        [ 9.8485,  9.9696,  4.9746],
        [ 9.8059,  9.9270,  4.9320]])

In [ ]:
torch.add(c, b, alpha=10)

tensor([[4.0900, 4.1021, 3.6026],
        [3.0417, 3.0538, 2.5543],
        [2.6161, 2.6282, 2.1287]])

## Subtraction
> Can be achieved using [`torch.sub()`](https://pytorch.org/docs/stable/generated/torch.sub.html#torch-sub) or normal python subtraction `-` operator
+ `torch.sub()` subtracts `other`, scaled by `alpha`, from `input`

```
  torch.sub(input, other, *, alpha=1, out=None)
```
> **Parameters**
+ `input` (Tensor) – the input tensor.
+ `other` (Tensor or Number) – the tensor or number to subtract from `input`
+ `alpha` (Number) – the multiplier for `other`
+ `out` (Tensor, optional) – the output tensor

In [ ]:
a = torch.tensor([3, 4, 5])
a

tensor([3, 4, 5])

In [ ]:
# using subtration symbol
a - 1

tensor([2, 3, 4])

In [ ]:
b = torch.rand(3)
b

tensor([0.9325, 0.5772, 0.0210])

In [ ]:
c = torch.rand(3)
c

tensor([0.3429, 0.6997, 0.4983])

In [ ]:
# using torch.sub() function
torch.sub(b, c, alpha=2)

tensor([ 0.2466, -0.8222, -0.9756])

## Element-wise multiplication
> Can be achieved using [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.sub.html#torch-sub) or normal python multiplication `*` operator

```
  torch.mul(input, other, *, out=None)
```
> **Parameters**
+ `input` (Tensor) – the input tensor.
+ `other` (Tensor or Number) – the tensor or number to multiply by `input`

In [ ]:
a = torch.rand(3)
a

tensor([0.5956, 0.7989, 0.0935])

In [ ]:
# using multiplication symbol
a * 10

tensor([5.9556, 7.9895, 0.9355])

In [ ]:
b = torch.rand(3, 1)
b

tensor([[0.1763],
        [0.5161],
        [0.5706]])

In [ ]:
c = torch.rand(3)
c

tensor([0.7132, 0.4484, 0.4831])

In [ ]:
torch.mul(b, c)

tensor([[0.1257, 0.0791, 0.0852],
        [0.3681, 0.2314, 0.2493],
        [0.4070, 0.2559, 0.2757]])

## Division
> Can be achieved using [`torch.div()`](https://pytorch.org/docs/stable/generated/torch.sub.html#torch-sub) or normal python division `/` operator

+ `torch.div()` divides each element of the `input` by the corresponding element of `other`

```
  torch.div(input, other, *, rounding_mode=None, out=None)
```
> **Parameters**
+ `input` (Tensor) – the input tensor.
+ `other` (Tensor or Number) – the tensor or number to multiply by `input`

In [ ]:
a = torch.rand(3)
a

tensor([0.1049, 0.6067, 0.1076])

In [ ]:
a / 2

tensor([0.0525, 0.3033, 0.0538])

In [ ]:
b = torch.rand(4, 4)
b

tensor([[0.3463, 0.2321, 0.7702, 0.2681],
        [0.8695, 0.1403, 0.5948, 0.2640],
        [0.9949, 0.5121, 0.6803, 0.9982],
        [0.7554, 0.0613, 0.7835, 0.9683]])

In [ ]:
c = torch.rand(4)
c

tensor([0.9833, 0.0111, 0.6783, 0.4034])

In [ ]:
torch.div(b, c)

tensor([[ 0.3521, 20.8814,  1.1355,  0.6646],
        [ 0.8843, 12.6242,  0.8770,  0.6544],
        [ 1.0118, 46.0823,  1.0029,  2.4745],
        [ 0.7682,  5.5127,  1.1551,  2.4004]])

> ▶️ **Up Next**  

> Matrix Multiplication
