# **Matrix Multiplication**
> 📝 **Note**  
> There's two main ways of carrying out multiplication in neural networks and deep learning:
+ Element-wise multiplication (as seen in the previous notebook)  
>> [`torch.mul(input, other, *, out=None)`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul)
+ Matrix multiplication (*dot product of matrices*)
>> [`torch.matmul(input, other, *, out=None)`](https://pytorch.org/docs/stable/generated/torch.matmul.html#torch.matmul)  
>> + Operator for matrix multiplication is `@`

> 📝 **Note**  
> Matrix multiplication needs to satisfy two rules:
1. **Inner dimensions** must match
>> + `(3, 2) @ (3, 2)` - won't work
>> + `(2, 3) @ (3, 2)` - will work
>> + `(3, 2) @ (2, 3)` - will work
2. Resulting tensor has the shape from the **outer dimension**
>> + `(3, 2) @ (2, 3)` - `(3, 3)`
>> + `(2, 3) @ (3, 2)` - `(2, 2)`

> 📚 **Reference**
+ A refresher on matrix multiplication can be found linked [`here`](https://byjus.com/maths/matrix-multiplication/), or [`here`](https://www.mathsisfun.com/algebra/matrix-multiplying.html) if you like

In [ ]:
# import torch
import torch
print(torch.__version__)

2.5.1+cu121


In [ ]:
# multiplying (2, 3) (3, 2)
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.7685, 0.5890],
        [0.7082, 0.7527]])

In [ ]:
# adding a third dimension
a = torch.rand(2, 2, 3)
a

tensor([[[0.8555, 0.5804, 0.2863],
         [0.4875, 0.0773, 0.7296]],

        [[0.3714, 0.1724, 0.1928],
         [0.5727, 0.7041, 0.8164]]])

In [ ]:
b = torch.rand(3, 2)
b

tensor([[0.1681, 0.7891],
        [0.4112, 0.3580],
        [0.9528, 0.6477]])

In [ ]:
torch.matmul(a, b)

tensor([[[0.6553, 1.0683],
         [0.8090, 0.8850]],

        [[0.3170, 0.4797],
         [1.1638, 1.2329]]])

In [ ]:
# multiplying (3, 2) (3, 2) matrix
# will yield an error due to mismatch
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### Dealing with shape mismatch
> To deal with tensor shape issues, we can transpose (reverse their shape) using [`Tensor.T`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.T)

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2).T)

tensor([[0.4361, 0.4147, 0.3250],
        [0.9530, 1.1176, 0.8903],
        [1.0676, 0.9844, 0.7692]])

> ▶️ **Up Next**  

> Tensor aggregation

