<a href="https://colab.research.google.com/github/Martinmbiro/PyTorch-tensor-basics/blob/main/08%20Tensor%20aggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensor Aggregation**
> This refers to combining / summarizing data from a single tensor or multiple tensors, and reducing that into a single statistic

> Aggregation operations are useful for extracting meaningful operations such as averages, sums, max, min values, e.t.c and are part of [`reduction operations`](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [2]:
# import torch
import torch
# print current torch version
torch.__version__

'2.5.1+cu121'

In [3]:
# create a tensor
t = torch.arange(1, 31, 2)
print(t)
print(t.size())

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])
torch.Size([15])


### max
> [`Tensor.max()`](https://pytorch.org/docs/stable/generated/torch.Tensor.max.html#torch.Tensor.max) and [`torch.max(input)`](https://pytorch.org/docs/stable/generated/torch.max.html#torch-max) will return the maximum value of all elements in the `input` tensor

In [4]:
t.max(), torch.max(t)

(tensor(29), tensor(29))

### argmax
> [`Tensor.argmax()`](https://pytorch.org/docs/stable/generated/torch.Tensor.argmax.html#torch-tensor-argmax) and [`torch.argmax(input)`](https://pytorch.org/docs/stable/generated/torch.argmax.html#torch-argmax) will return the indices of the maximum value of all elements in the `input` tensor

In [5]:
t.argmax(), torch.argmax(t)

(tensor(14), tensor(14))

### mim
> `Tensor.mim()` and `torch.min(input)` will return the minimum value of all elements in the `input` tensor

In [6]:
t.min(), torch.min(t)

(tensor(1), tensor(1))

### argmin
> `Tensor.argmin()` and `torch.argmin(input)` will return the indices of the minimum value(s) of the flattened tensor or along a dimension

In [7]:
t.argmin(), torch.argmin(t)

(tensor(0), tensor(0))

### sum
> `Tensor.sum()` and `torch.sum(input)` will return the sum of all elements in the `input` tensor

In [8]:
t.sum(), torch.sum(t)

(tensor(225), tensor(225))

### median
> `Tensor.median()` and `torch.median(input)` will return the median of the values in `input`

In [9]:
t.median(), torch.median(t)

(tensor(15), tensor(15))

### mean
> [`Tensor.mean()`](https://pytorch.org/docs/stable/generated/torch.Tensor.mean.html#torch-tensor-mean) and [`torch.mean(input)`](https://pytorch.org/docs/stable/generated/torch.mean.html#torch-mean) will return the mean value of all elements in the `input` tensor

> 📝 **Note**   
+ Input must be floating point or complex.

In [10]:
# check dtype of the tensor t
t.dtype

torch.int64

In [11]:
# returning mean
t.type(torch.float32).mean(), torch.mean(t.type(torch.float32))

(tensor(15.), tensor(15.))

### Unique
> [`torch.unique(input, sorted=True, return_inverse=False, return_counts=False`](https://pytorch.org/docs/stable/generated/torch.unique.html#torch.unique) and [`torch.Tensor.unique()`](https://pytorch.org/docs/stable/generated/torch.Tensor.unique.html#torch-tensor-unique) will return the unique elements of the `input` tensor
+ `return_inverse` _(bool)_ – Whether to also return the indices for where elements in the original input ended up in the returned unique list.
+ `return_counts` _(bool)_ – Whether to also return the counts for each unique element.

In [19]:
# create a tensor
a = torch.randint(low=1, high=5, size=(30,))
a

tensor([4, 1, 2, 1, 4, 3, 1, 3, 2, 4, 1, 1, 4, 2, 4, 1, 3, 2, 3, 3, 1, 3, 3, 2,
        2, 3, 3, 1, 4, 1])

In [20]:
# return unique elements
a.unique()

tensor([1, 2, 3, 4])

In [21]:
# return unique elements with their counts
a.unique(return_counts=True)

(tensor([1, 2, 3, 4]), tensor([9, 6, 9, 6]))

### Total number of elements
> [`torch.numel(input)`](https://pytorch.org/docs/stable/generated/torch.numel.html#torch.numel) and [`Tensor.numel()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numel.html#torch.Tensor.numel) will return the total number of elements in the input tensor.

In [24]:
# create a tensor
b = torch.randn(2, 2, 4)
b.numel()

16

> ▶️ **Up Next**  

>Reshaping, Viewing, Flattening & Stacking Tensors