# **Reshaping, Viewing, Flattening & Stacking Tensors**
> Manipulating tensors with operations such as _reshaping_, _squeezing_, _unsqueezing_, _stacking_, _viewing_, _permuting_, and _flattening_ revolves around changing the structure, shape or dimension of the tensors for numerical computation tasks.

> 📝 **Note**
+ These manipulations do not alter the underlying data
+ These methods ensure that the elements of your tensors are compatible with other tensors in terms of numerical computation

In [ ]:
# import torch
import torch
# print version
torch.__version__

'2.5.1+cu121'

### Reshaping
> `torch.reshape(input, shape)` & `Tensor.reshape(*shape)` return a tensor with the same data and number of elements as `input`, but with the specified `shape`  

> 📝 **Note**  
+ `shape` (tuple of `int`) – the new `shape`
+ Ensure that the new `shape` of the tensor produces the same _number_ of elements as the original tensor

In [ ]:
# create a tensor
a = torch.arange(12)

# print tensor and shape
print(a)
print(a.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])


In [ ]:
a.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
a.reshape(4, 3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [ ]:
a.reshape(-1, 6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [ ]:
print(a.reshape(1, -1, 6), '\n')
print(a.reshape(1, -1, 6).shape)

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]]) 

torch.Size([1, 2, 6])


In [ ]:
print(a.reshape(2, 2, 3), '\n')
print(a.reshape(2, 2, 3).shape)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]]) 

torch.Size([2, 2, 3])


### [`torch.Tensor.view`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html#torch-tensor-view)
> Same as `torch.Tensor.reshape()`, `torch.Tensor.view()` is a way of changing the shape of a tensor, but while sharing the same memory and _not_ making copies

> 📝 **Note**  
+ A **view** is a way of creating a tensor that shares the same data as the original tensor but has a different shape, but does not copy the data; only changing the way the data is interpreted
+ A view shares memory with the original data, hence modifying either will be reflected in the other

In [ ]:
# create a tensor
a = torch.arange(1, 13)
print(a.shape)
print(a)

torch.Size([12])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [ ]:
# creating a view of the above tensor
b = a.view(2, 2, 3)
print(b.shape, '\n')
print(b)

torch.Size([2, 2, 3]) 

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [ ]:
# altering one of the elements
b[1, 1, 2] = 99

In [ ]:
# printing the original tensor
print(a)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 99])


### Flattening
[`torch.flatten(input, start_dim=0, end_dim=-1)`](https://pytorch.org/docs/stable/generated/torch.flatten.html#torch.flatten) and [`torch.Tensor.flatten(start_dim=0, end_dim=-1)`](https://pytorch.org/docs/stable/generated/torch.Tensor.flatten.html#torch-tensor-flatten) will flatten `input` by reshaping it into a one-dimensional tensor.

In [ ]:
# create a tensor
a = torch.arange(12).reshape(3, 2, 2)
print(a)

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])


In [ ]:
a.flatten()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.flatten(1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### Squeezing
> `Tensor.squeeze(dim=None)` & [`torch.squeeze(input, dim=None)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html#torch-squeeze) return a tensor with all specified dimensions of `input` of size `1` removed
+ When `dim` is given, a squeeze operation is done only in the given dimension(s)

In [ ]:
# create a tensor
a = torch.zeros(1, 3, 1)
a

tensor([[[0.],
         [0.],
         [0.]]])

In [ ]:
print(a.squeeze())
print(a.squeeze().shape)

tensor([0., 0., 0.])
torch.Size([3])


In [ ]:
# specifying a particular dimension
a.squeeze(2).shape

torch.Size([1, 3])

### Unsqueezing
> [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html#torch.unsqueeze) & `Tensor.unsqueeze(dim)` returns a new tensor with a dimension of size `1` inserted at the specified position

In [ ]:
# create a tensor
a = torch.arange(4)
print(a.shape)
print(a)

torch.Size([4])
tensor([0, 1, 2, 3])


In [ ]:
# add a dimension at position 0
a.unsqueeze(0).shape

torch.Size([1, 4])

In [ ]:
# add a dimension at position 1
a.unsqueeze(1).shape
print(a.unsqueeze(1))

tensor([[0],
        [1],
        [2],
        [3]])


### Stacking

#### [`torch.stack(tensors, dim=0, *, out=None)`](https://pytorch.org/docs/stable/generated/torch.stack.html#torch-stack)
> Concatenates a set of tensors along a **new** dimension
+ All tensors need to be of the same size

In [ ]:
# create a random tensor
a = torch.rand(2, 3)
a

tensor([[0.9024, 0.4322, 0.4606],
        [0.7702, 0.3520, 0.9231]])

In [ ]:
# stack along dimension 0
print(torch.stack((a, a), dim=0))
print('\n', torch.stack((a, a), dim=0).shape)

tensor([[[0.9024, 0.4322, 0.4606],
         [0.7702, 0.3520, 0.9231]],

        [[0.9024, 0.4322, 0.4606],
         [0.7702, 0.3520, 0.9231]]])

 torch.Size([2, 2, 3])


In [ ]:
# stack along dimension 1
print(torch.stack((a, a), dim=1))
print('\n', torch.stack((a, a), dim=1).shape)

tensor([[[0.9024, 0.4322, 0.4606],
         [0.9024, 0.4322, 0.4606]],

        [[0.7702, 0.3520, 0.9231],
         [0.7702, 0.3520, 0.9231]]])

 torch.Size([2, 2, 3])


In [ ]:
# stack along dimension 2
print(torch.stack((a, a), dim=2))
print('\n', torch.stack((a, a), dim=2).shape)

tensor([[[0.9024, 0.9024],
         [0.4322, 0.4322],
         [0.4606, 0.4606]],

        [[0.7702, 0.7702],
         [0.3520, 0.3520],
         [0.9231, 0.9231]]])

 torch.Size([2, 3, 2])


#### [`torch.cat(tensors, dim=0, *, out=None)`](https://pytorch.org/docs/stable/generated/torch.cat.html#torch-cat)
> Concatenates a set of tensors along an **existing** dimension

In [ ]:
# create a new tensor
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a, '\n\n', b)

tensor([[0.5780, 0.6131, 0.1284],
        [0.8147, 0.2230, 0.6966]]) 

 tensor([[0.4935, 0.1515, 0.3375],
        [0.0354, 0.6335, 0.5362]])


In [ ]:
# concatenate along dim 0
print(torch.cat((a, b), dim=0))
print(torch.cat((a, b), dim=0).shape)

tensor([[0.5780, 0.6131, 0.1284],
        [0.8147, 0.2230, 0.6966],
        [0.4935, 0.1515, 0.3375],
        [0.0354, 0.6335, 0.5362]])
torch.Size([4, 3])


In [ ]:
# concatenate along dim 1
print(torch.cat((a, b), dim=1))
print(torch.cat((a, b), dim=1).shape)

tensor([[0.5780, 0.6131, 0.1284, 0.4935, 0.1515, 0.3375],
        [0.8147, 0.2230, 0.6966, 0.0354, 0.6335, 0.5362]])
torch.Size([2, 6])


### Permute
> [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html#torch-permute) and [`Tensor.permute(*dims)`](https://pytorch.org/docs/stable/generated/torch.Tensor.permute.html#torch-tensor-permute) return a _view_ of the original tensor `input` with its dimensions permuted / rearranged
+ `input` (Tensor) – the input tensor.
+ `dims` (tuple of int) – The desired ordering of dimensions

In [ ]:
# random tensor
#         index 0, 1, 2
x = torch.randn(1, 3, 2)
x

tensor([[[ 2.5500,  1.1350],
         [-0.8323, -2.0097],
         [ 0.4560, -0.8896]]])

In [ ]:
# re-order the original dimensions
x.permute(1, 2, 0)

tensor([[[ 2.5500],
         [ 1.1350]],

        [[-0.8323],
         [-2.0097]],

        [[ 0.4560],
         [-0.8896]]])

In [ ]:
# check shape
x.permute(1, 2, 0).shape

torch.Size([3, 2, 1])

> ▶️ **Up Next**  

> Tensor indexing
