<a href="https://colab.research.google.com/github/Martinmbiro/PyTorch-tensor-basics/blob/main/11%20PyTorch%20tensors%20%26%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[`PyTorch`](https://pytorch.org/) [`Tensors`](https://pytorch.org/docs/stable/tensors.html#) & [`Numpy`](https://numpy.org/)**
> Since `NumPy` is a popular numerical computation library, `PyTorch` has functionality to interact with it, through two main methods:
+ [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html#torch.from_numpy)
+ [`Tensor.numpy(*, force=False)`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html#torch-tensor-numpy)

### [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html#torch.from_numpy)
> Creates a [`Tensor`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor) from a [`numpy.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray)
+ The returned `Tensor` and `ndarray` share the same memory.
+ Modifications to the `Tensor` will be reflected in the `ndarray` and vice versa
+ The returned `Tensor` is not resizable.

In [ ]:
# import numpy, torch
import numpy as np
import torch

In [ ]:
# creating an ndarray
a = np.zeros(12).reshape(2, 2, 3)
a

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# creating a tensor from ndarray a
t = torch.from_numpy(a)
t

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

In [ ]:
# change a value in the tensor
t[0, 1, 2] = 1

# display the ndarray
a

array([[[0., 0., 0.],
        [0., 0., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### [`Tensor.numpy(*, force=False)`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html#torch-tensor-numpy)
> Returns the tensor as a NumPy `ndarray`

In [ ]:
# create a tensor
b = torch.arange(1, 7).reshape(1, 3, 2)
b

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [ ]:
# create a numpy array
n = b.numpy()

n[0, 1, 1] = 10

In [ ]:
# display original tensor
b

tensor([[[ 1,  2],
         [ 3, 10],
         [ 5,  6]]])

> ▶️ **Up Next**  

> Tensor reproducibility

