# **Reproducibility**
> Reproducibility is a way to reduce randomness in creation of tensors, making sure that you get the same or very similar results when the code is run multiple times

In [ ]:
# import torch
import torch
torch.__version__

'2.5.1+cu121'

In [ ]:
# create random tensors
a = torch.rand(2, 3)
b = torch.rand(2, 3)

# print a, b
print(a)
print('\n', b)

# check for equality
print('\n', a == b)

tensor([[0.1266, 0.2074, 0.4046],
        [0.9223, 0.8818, 0.5804]])

 tensor([[0.9194, 0.9376, 0.7753],
        [0.1787, 0.0154, 0.3168]])

 tensor([[False, False, False],
        [False, False, False]])


> 📝 **Note**
+ [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html#torch-manual-seed) sets the seed for generating random numbers on all devices, such that tensors generated will be of the same value

In [ ]:
# setting random seed
torch.manual_seed(42)

# create random tensor
c = torch.rand(2, 3)

# setting the same random seed
torch.manual_seed(42)

d = torch.rand(2, 3)

# print a, b
print(c)
print('\n', d)

# check for equality
print('\n', c == d)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

 tensor([[True, True, True],
        [True, True, True]])


> ▶️ **Up Next**  

> Device agnostic code