# **Device-agnostic Code**
> Deep learning algorithms require a lot of numerical computation (matrix multiplication) which could run faster on NVIDIA GPU's with `CUDA`, much faster than they could on a CPU

> 💡 **Info**  
+ `CUDA` is a platform and API that allows NVIDIA GPU's to be used for general purpose computing tasks and not just graphics
+ PyTorch also makes it possible to run tensors on Apple Silicon (M1/M2/M3) chips
+ Google colab provides access to an NVIDIA GPU, either free or on premium terms

> 🔥 **Pro tip**  
> Here's how to set up the free GPU on Google Colab
+ Go to the 'Runtime' tab
+ Select 'Change runtime type'
+ Select the hardware of your choice

> _For this particular notebook, I've chosen my hardware as `T4 GPU`_

In [ ]:
# import torch
import torch
torch.__version__

'2.5.1+cu121'

### Checking for NVIDIA GPU

In [ ]:
# to check if we've got access to an NVIDIA GPU:
!nvidia-smi

Sun Dec 15 10:38:19 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   76C    P0              34W /  70W |    121MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### Test access to GPU
> If the line below return `True`, PyTorch has access to a GPU

In [ ]:
# NVIDIA GPU available?
torch.cuda.is_available()

True

In [ ]:
# how many NVIDIA GPU's avalable?
torch.cuda.device_count()

1

In [ ]:
# Apple Silicon GPU available?
torch.backends.mps.is_available()

False

### Setting device type
> Setting device type depending on the available hardware

In [ ]:
if torch.cuda.is_available():
  device = 'cuda' # use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
  device = 'mps' # use Apple Silicon GPU (if available)
else:
  device = 'cpu' # otherwise, result to use CPU

### Putting tensors and models on GPU
> [`torch.Tensor.to()`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html#torch-tensor-to) performs Tensor `torch.dtype` and/or `torch.device` conversion, inferred from the arguments

> 📝 **Note**  
+ By default, PyTorch models and tensors are created on the CPU
+ `torch.Tensor.to()` returns a copy of that tensor, meaning it will be present on both the CPU & GPU (unless it's overwritten)

#### Changing `dtype` with `Tensor.to()`

In [ ]:
# create a tensor (int type)
a = torch.arange(12).reshape(3, 4)
print(a)
print(a.dtype, a.device)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.int64 cpu


In [ ]:
# change dtype
a = a.to(dtype=torch.float32)
print(a)
print(a.dtype, a.device)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.float32 cpu


#### Changing `device` with `Tensor.to()`



In [ ]:
a = a.to(device=device)
print(a)
print(a.dtype, a.device)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], device='cuda:0')
torch.float32 cuda:0


### Moving tensors back to CPU
> This might be the case when you want to interact with the tensors in [`NumPy`](https://numpy.org), which does not leverage GPU
+ Try using [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) on the tensor living on the GPU

In [ ]:
# this returns an error, but luckily, pytorch
# gives us a solution to work around this
a.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# overwriting the variable a to be an ndarray
a = a.cpu().numpy()
print(a)
print(a.dtype)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
float32


In [ ]:
# checking the type
type(a)

numpy.ndarray

> ▶️ **Up Next**  

> Pytorch workflow with regression